version: '3.6'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dathena
        ports:
            - "54333:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        restart:
            always
        command: >
            sh -c "source ./script/wait-for-postgres.sh db
            && source ./script/entrypoint.sh"
        depends_on:
          - db
          - rabbitmq
#          - celery_worker
    rabbitmq:
        image: rabbitmq:3.7-alpine
# can't get this to work
#    celery_worker:
#        <<: *app
#        command: celery -A app worker --loglevel=info
#        ports: []
#        depends_on:
#          - rabbitmq
#          - db
volumes:
  postgres_data:
