version: '3.6'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dathena
        ports:
            - "54333:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        restart:
            always
        command: >
            sh -c "source ./wait-for-postgres.sh db
            && source ./entrypoint.sh"
        depends_on:
          - db

