# Generated by Django 2.2 on 2019-04-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('total_docs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialityLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='DoctypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('total_docs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctypeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLabel',
            fields=[
                ('shortName', models.CharField(max_length=99, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_docs', models.IntegerField()),
                ('language_label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.LanguageLabel')),
            ],
        ),
    ]
